# Generated by Django 4.2.27 on 2026-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient_role",
            field=models.CharField(
                choices=[
                    ("faculty", "Faculty"),
                    ("student", "Student"),
                    ("all", "All"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
