# Generated by Django 4.2.27 on 2026-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_alter_notification_recipient_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="qualified_faculties", to="admin_app.subject"
            ),
        ),
    ]
