# Generated by Django 4.2.27 on 2026-01-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_faculty_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammarks",
            name="admit_card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="admin_app.admitcard",
            ),
        ),
    ]
