# Generated by Django 4.2.27 on 2026-01-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_alter_exammarks_admit_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="degree_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolled_students",
                to="admin_app.degreeprogram",
            ),
        ),
    ]
