# Generated by Django 4.2.27 on 2026-02-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_student_degree_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculties",
                to="admin_app.department",
            ),
        ),
    ]
