# Generated by Django 4.2.19 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject',
            field=models.ManyToManyField(blank=True, to='registration.subject'),
        ),
    ]
