# Generated by Django 4.2.19 on 2025-02-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_subject_faculty_salary_faculty_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
